### ISSUE TITLE
Step 7: MCP Tool Handler Implementation

### ISSUE THREAD

**Issue by crdant** [crdant/replicated-mcp-server#7]
## Overview
Implement MCP tool handlers that bridge MCP requests to API calls, completing the integration between the MCP protocol and Replicated API.

## Deliverables
- [ ] Complete `pkg/mcp/handlers.go` with all tool implementations
- [ ] MCP request parsing and validation
- [ ] API client method integration
- [ ] MCP response formatting
- [ ] Error handling in MCP format

## Dependencies
- Step 1 (Configuration and Logging) - for config and logging
- Step 2 (Data Models) - for type safety and validation
- Step 4 (MCP Server Foundation) - for tool definitions and server
- Step 5-6 (API Implementation) - for API client methods

## Estimated Effort
2-3 days

**See plan.md for detailed requirements and implementation notes.**

**Comment by crdant** [comment]
## Linting Rule Restoration Reminder

During Step 4 (MCP Server Foundation), we temporarily added exclusions to `.golangci.yml` for:

1. **dupl warnings** in `pkg/mcp/tools.go` - Currently excluded because tool definitions follow intentionally similar patterns for foundation consistency
2. **unparam warnings** for `registerTools` and `registerResources` methods - Currently excluded because they always return nil in the foundation

### Action Required for Step 7:

When implementing the actual MCP tool handlers, please **restore these linting rules** by removing the following exclusions from `.golangci.yml`:

```yaml
      - linters:
          - dupl
        path: pkg/mcp/tools\.go$
        text: "lines are duplicate"
      - linters:
          - unparam
        path: pkg/mcp/server\.go$
        text: "registerTools.*result 0.*is always nil|registerResources.*result 0.*is always nil"
```

### Why restore them:

- **dupl**: Once handlers are implemented, the tool definitions will have differentiated business logic and should not be flagged as duplicates
- **unparam**: The register methods will likely return actual errors during handler registration, making the return values meaningful

This ensures we maintain code quality standards once the actual implementation differentiates the foundation patterns.

**Related commits:**
- Foundation implementation: f6f5217
- Linting exclusions: 7224eb9
